add docker-compose plugin

diff --git a/.github/workflows/deploy.pod.yml b/.github/workflows/deploy.pod.yml
--- a/.github/workflows/deploy.pod.yml
+++ b/.github/workflows/deploy.pod.yml
@@ -146,16 +146,26 @@ jobs:
               echo "Node.js already installed: $(node -v)"
             fi
 
-            sudo apt-get update && sudo apt-get install -y docker.io
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+            else
+              echo "Docker already installed: $(docker --version)"
+              exit 0
+            fi
+            sudo apt-get install ca-certificates curl
+            sudo install -m 0755 -d /etc/apt/keyrings
+            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+            sudo chmod a+r /etc/apt/keyrings/docker.asc
+            echo \
+            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
+            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+            sudo apt-get update
+            
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
             sudo groupadd docker
             
-            sudo usermod -aG docker $USER
-            sudo apt-get install docker-compose-plugin          
-
-
-
-           
-
+            sudo usermod -aG docker $USER          
 
             sudo apt-get update -y
             sudo apt-get install -y nginx
@@ -177,6 +187,9 @@ jobs:
             sudo mkdir -p /usr/lib/docker/cli-plugins
             
             sudo curl -L "https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/lib/docker/cli-plugins/docker-compose
+            sudo curl -L "https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-$(uname -s)-$(uname -m)" \
+            -o /usr/lib/docker/cli-plugins/docker-compose
+
             sudo mv /usr/lib/docker/cli-plugins/docker-compose
             sudo chmod +x /usr/lib/docker/cli-plugins/docker-compose
 
